apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  namespace: pricelist
  name: hook-presync-pricelist-config
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
        - name: slack-notification
          image: curlimages/curl
          command:
            - "curls"
            - "-X"
            - "POST"
            - "--data-urlencode"
            - "payload={\"text\": \"App Sync succeeded\", \"icon_emoji\": \":ghost:\"}"
            - "https://hooks.slack.com/services/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"
          resources:
            requests:
              memory: "32Mi"
              cpu: "32m"
            limits:
              memory: "64Mi"
              cpu: "64m"
      restartPolicy: Never
